import type { Job, Company } from "@/types/database.types";

export const mockCompanies: Company[] = [
  {
    id: "c1",
    name: "TechNova",
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "c2",
    name: "CloudSync",
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "c3",
    name: "DataFlow",
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "c4",
    name: "PixelCraft",
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "c5",
    name: "NexGen Solutions",
    logo_url: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "c6",
    name: "InnovateTech",
    logo_url: null,
    created_at: new Date().toISOString(),
  },
];

export const mockJobs: Job[] = [
  {
    id: "j1",
    title: "Frontend Developer",
    company_id: "c1",
    location: "Jakarta, Indonesia",
    job_type: "Full-time",
    experience_level: "Junior",
    salary_range: "Rp 8 - 15 Juta",
    skills: ["React", "Next.js", "TypeScript"],
    description:
      "Build modern web applications using React and Next.js. Work with a dynamic team to deliver high-quality user experiences.",
    created_at: new Date().toISOString(),
    company: mockCompanies[0],
  },
  {
    id: "j2",
    title: "Backend Engineer",
    company_id: "c2",
    location: "Bandung, Indonesia",
    job_type: "Full-time",
    experience_level: "Mid-level",
    salary_range: "Rp 12 - 20 Juta",
    skills: ["Node.js", "PostgreSQL", "Docker"],
    description:
      "Design and implement scalable backend services. Experience with microservices architecture is a plus.",
    created_at: new Date().toISOString(),
    company: mockCompanies[1],
  },
  {
    id: "j3",
    title: "UI/UX Designer",
    company_id: "c3",
    location: "Remote",
    job_type: "Remote",
    experience_level: "Junior",
    salary_range: "Rp 7 - 12 Juta",
    skills: ["Figma", "Adobe XD", "Prototyping"],
    description:
      "Create beautiful and intuitive user interfaces. Collaborate with developers to bring designs to life.",
    created_at: new Date().toISOString(),
    company: mockCompanies[2],
  },
  {
    id: "j4",
    title: "Full Stack Developer",
    company_id: "c4",
    location: "Surabaya, Indonesia",
    job_type: "Full-time",
    experience_level: "Mid-level",
    salary_range: "Rp 15 - 25 Juta",
    skills: ["React", "Node.js", "MongoDB"],
    description:
      "Build end-to-end web applications. Strong knowledge of both frontend and backend technologies required.",
    created_at: new Date().toISOString(),
    company: mockCompanies[3],
  },
  {
    id: "j5",
    title: "DevOps Engineer",
    company_id: "c5",
    location: "Jakarta, Indonesia",
    job_type: "Full-time",
    experience_level: "Senior",
    salary_range: "Rp 20 - 35 Juta",
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    description:
      "Manage cloud infrastructure and deployment pipelines. Ensure high availability and scalability of services.",
    created_at: new Date().toISOString(),
    company: mockCompanies[4],
  },
  {
    id: "j6",
    title: "Mobile Developer",
    company_id: "c6",
    location: "Yogyakarta, Indonesia",
    job_type: "Part-time",
    experience_level: "Junior",
    salary_range: "Rp 5 - 10 Juta",
    skills: ["React Native", "TypeScript", "Firebase"],
    description:
      "Develop cross-platform mobile applications using React Native. Focus on performance and user experience.",
    created_at: new Date().toISOString(),
    company: mockCompanies[5],
  },
  {
    id: "j7",
    title: "Data Analyst",
    company_id: "c1",
    location: "Jakarta, Indonesia",
    job_type: "Full-time",
    experience_level: "Entry-level",
    salary_range: "Rp 6 - 12 Juta",
    skills: ["Python", "SQL", "Tableau"],
    description:
      "Analyze data to drive business decisions. Create reports and dashboards for stakeholders.",
    created_at: new Date().toISOString(),
    company: mockCompanies[0],
  },
  {
    id: "j8",
    title: "Product Manager",
    company_id: "c2",
    location: "Remote",
    job_type: "Remote",
    experience_level: "Mid-level",
    salary_range: "Rp 18 - 30 Juta",
    skills: ["Agile", "Scrum", "Product Strategy"],
    description:
      "Lead product development from ideation to launch. Work with cross-functional teams to deliver user value.",
    created_at: new Date().toISOString(),
    company: mockCompanies[1],
  },
];
